const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const cors = require("cors");
const path = require("path");
const fs = require("fs");
const multer = require("multer");
const { ethers } = require("ethers");
const crypto = require("crypto");
const {
  summarizeProposalProblem,
  OLLAMA_MODEL,
} = require("./services/proposalSummaryService");

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));
app.use("/uploads", express.static(path.join(__dirname, "uploads")));

const uploadDir = path.join(__dirname, "uploads");
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, uploadDir);
  },
  filename: function (req, file, cb) {
    cb(null, Date.now() + path.extname(file.originalname));
  }
});
const upload = multer({ storage: storage });

const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

const rpcUrl = process.env.RPC_URL || "http://127.0.0.1:8545";
const addressFilePath =
  process.env.ADDRESS_FILE || path.join(__dirname, "address.json");
const port = Number(process.env.PORT || 3001);

// ─────────────────────────────────────────────
//  WEB3 BLOCKCHAIN SETUP (Hardhat localhost)
// ─────────────────────────────────────────────

const provider = new ethers.JsonRpcProvider(rpcUrl);

// Read deployed contract metadata generated by deployment service.
const contractJSON = require("./artifacts/contracts/OffGridDAO.sol/OffGridDAO.json");
const { encrypt, decrypt } = require("./lib/crypto");
let contractAddress = "";
let contractAbi = contractJSON.abi;
let deploymentMetadata = null;
try {
  const raw = fs.readFileSync(addressFilePath, "utf8");
  deploymentMetadata = JSON.parse(raw);
  contractAddress = deploymentMetadata.contractAddress;
  if (
    Array.isArray(deploymentMetadata.abi) &&
    deploymentMetadata.abi.length > 0
  ) {
    contractAbi = deploymentMetadata.abi;
  }
} catch (e) {
  console.warn(
    "⚠️ Warning: address.json not found. Run deployment script first.",
  );
}

let daoContract;
if (contractAddress) {
  daoContract = new ethers.Contract(contractAddress, contractAbi, provider);
}

// Admin signer (Hardhat Account #0) for creating proposals and allocating tokens
const ADMIN_KEY =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const adminSigner = new ethers.Wallet(ADMIN_KEY, provider);
let adminContract;
if (daoContract) {
  adminContract = daoContract.connect(adminSigner);
}

// Transaction Feed history cache
const transactionFeed = [];

// Track which cards have been initialized with tokens
const initializedCards = new Set();

// ─────────────────────────────────────────────
//  VOTER REGISTRY (Mapped to Hardhat Private Keys)
// ─────────────────────────────────────────────
function encryptPayload(text, pin) {
  const key = crypto.pbkdf2Sync(pin, "salt", 100000, 32, "sha256");
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  let encrypted = cipher.update(text, "utf8", "hex");
  encrypted += cipher.final("hex");
  const authTag = cipher.getAuthTag().toString("hex");
  return { iv: iv.toString("hex"), encrypted, authTag };
}

function decryptPayload(encryptedObj, pin) {
  const key = crypto.pbkdf2Sync(pin, "salt", 100000, 32, "sha256");
  const decipher = crypto.createDecipheriv(
    "aes-256-gcm",
    key,
    Buffer.from(encryptedObj.iv, "hex"),
  );
  decipher.setAuthTag(Buffer.from(encryptedObj.authTag, "hex"));
  let decrypted = decipher.update(encryptedObj.encrypted, "hex", "utf8");
  decrypted += decipher.final("utf8");
  return decrypted;
}

const voters = {
  Metro_Card_001: {
    name: "Vaibhav Gupta",
    avatar: "👵",
    privateKey:
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    ward: "Sector 7, Green Park Colony",
  },
  Metro_Card_002: {
    name: "OG Pratyush Mehra",
    avatar: "👴",
    privateKey:
      "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
    ward: "Sector 12, Riverside",
  },
  Metro_Card_003: {
    name: "Suryansh Mishra",
    avatar: "👩",
    privateKey:
      "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
    ward: "Sector 3, Market Road",
  },
};

for (const cardId in voters) {
  const wallet = new ethers.Wallet(voters[cardId].privateKey);
  voters[cardId].wallet = wallet.address;
  voters[cardId].encryptedPayload = encryptPayload(voters[cardId].privateKey, "1234");
  delete voters[cardId].privateKey; // Wiped from memory
}

const fallbackWallet = new ethers.Wallet(
  "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6",
);
const fallbackPayload = encryptPayload(fallbackWallet.privateKey, "1234");

function getVoter(cardId) {
  if (voters[cardId]) {
    return { cardId, ...voters[cardId] };
  }
  return {
    cardId,
    name: "Community Member",
    avatar: "🧑",
    encryptedPayload: fallbackPayload,
    wallet: fallbackWallet.address,
    ward: "Local Resident",
  };
}

// Helper to read all proposals from blockchain
async function readAllProposals() {
  const proposalsData = [];
  if (!daoContract) return proposalsData;
  try {
    const count = await daoContract.proposalCount();
    for (let i = 1; i <= Number(count); i++) {
      const p = await daoContract.getProposal(i);
      proposalsData.push({
        id: Number(p.id),
        title: p.title,
        description: p.description,
        category: p.category,
        fundsRequested: Number(p.fundsRequested),
        votes: Number(p.votes),
        status: p.active ? "active" : "inactive",
        imageUrl: p.imageUrl,
      });
    }
  } catch (e) {
    console.error("Error reading proposals:", e);
  }
  return proposalsData;
}

let currentVoter = null;

function ensureContractReady(res) {
  if (!daoContract || !adminContract || !contractAddress) {
    sendEncrypted(res, 503, {
      error: "Contract not ready yet. Wait for deployment to complete.",
      addressFilePath,
    });
    return false;
  }
  return true;
}

function buildEncryptedPayload(data) {
  return { payload: encrypt(JSON.stringify(data)) };
}

function sendEncrypted(res, statusCode, data) {
  return res.status(statusCode).json(buildEncryptedPayload(data));
}

function readEncryptedBody(req) {
  const body = req.body;

  if (body && typeof body === "object" && typeof body.payload === "string") {
    const decrypted = decrypt(body.payload);
    if (!decrypted) return null;
    try {
      return JSON.parse(decrypted);
    } catch (_error) {
      return null;
    }
  }

  // Backward compatibility for non-encrypted callers.
  if (body && typeof body === "object") {
    return body;
  }

  if (typeof body === "string") {
    const decrypted = decrypt(body);
    if (!decrypted) return null;
    try {
      return JSON.parse(decrypted);
    } catch (_error) {
      return null;
    }
  }

  return null;
}

// ─────────────────────────────────────────────
//  API ROUTES
// ─────────────────────────────────────────────

app.post("/upload", upload.single("image"), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "No image file provided." });
  }
  const fileUrl = `http://localhost:3001/uploads/${req.file.filename}`;
  return res.json({ imageUrl: fileUrl });
});

app.get("/contract", (req, res) => {
  if (!contractAddress) {
    return sendEncrypted(res, 503, {
      error: "Contract metadata unavailable",
      addressFilePath,
    });
  }

  return sendEncrypted(res, 200, {
    name:
      (deploymentMetadata && deploymentMetadata.contractName) || "OffGridDAO",
    contractAddress,
    abi: contractAbi,
    rpcUrl,
    deployedAt: deploymentMetadata && deploymentMetadata.deployedAt,
  });
});

// Get all proposals from the SMART CONTRACT
app.get("/proposals", async (req, res) => {
  if (!ensureContractReady(res)) return;
  return sendEncrypted(res, 200, await readAllProposals());
});

// Create a new proposal (from admin panel)
app.post("/proposals", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }

  const { title, description, category, fundsRequested, imageUrl } = data;
  if (!title || !fundsRequested) {
    return sendEncrypted(res, 400, {
      error: "Missing title or fundsRequested",
    });
  }

  try {
    console.log(`📝 Creating new proposal: "${title}"...`);
    const tx = await adminContract.createProposal(
      title,
      description || "",
      category || "General",
      fundsRequested,
      imageUrl || ""
    );
    await tx.wait();
    console.log(`✅ Proposal created on-chain! TX: ${tx.hash}`);

    // Re-read all proposals and broadcast to all dashboards
    const allProposals = await readAllProposals();
    io.emit("proposals-updated", allProposals);

    return sendEncrypted(res, 200, {
      success: true,
      transactionHash: tx.hash,
    });
  } catch (e) {
    console.error("❌ Failed to create proposal:", e.reason || e.message);
    return sendEncrypted(res, 500, {
      error: e.reason || "Failed to create proposal",
    });
  }
});

app.post("/proposals/summarize-problem", async (req, res) => {
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }

  const title = typeof data.title === "string" ? data.title.trim() : "";
  const description =
    typeof data.description === "string" ? data.description.trim() : "";

  if (!title) {
    return sendEncrypted(res, 400, {
      error: "Proposal title is required",
    });
  }

  try {
    const summary = await summarizeProposalProblem({
      title,
      description,
    });

    return sendEncrypted(res, 200, {
      summary,
      model: OLLAMA_MODEL,
    });
  } catch (error) {
    console.error("❌ Summary generation failed:", error.message);
    return sendEncrypted(res, 502, {
      error: "Could not generate proposal summary",
    });
  }
});

// NFC Scan → Identify Voter + Check Token Balance
app.get("/scan", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const cardId = req.query.cardId || "Unknown_Card";
  console.log(`\n📡 NFC SCAN DETECTED: ${cardId}`);

  const voter = getVoter(cardId);
  currentVoter = voter;

  // Allocate tokens on first scan if not already done
  let tokenBalance = 0;
  try {
    if (!initializedCards.has(cardId) && adminContract) {
      console.log(
        `🪙 First scan for ${cardId} — allocating 1000 tokens on-chain...`,
      );
      const allocTx = await adminContract.allocateTokens(voter.wallet, 1000);
      await allocTx.wait();
      initializedCards.add(cardId);
    }
    // Read balance from blockchain
    tokenBalance = Number(await daoContract.getTokenBalance(voter.wallet));
  } catch (e) {
    console.error("Token allocation error:", e.reason || e.message);
  }

  const txEntry = {
    id: transactionFeed.length + 1,
    type: "IDENTITY_VERIFY",
    hash:
      "0x" +
      require("crypto")
        .createHash("md5")
        .update("identity" + Date.now())
        .digest("hex")
        .slice(0, 40),
    timestamp: new Date().toISOString(),
  };
  transactionFeed.push(txEntry);

  // Broadcast to dashboard with token balance and encrypted payload
  io.emit("card-scanned", {
    voter: {
      name: voter.name,
      avatar: voter.avatar,
      wallet: voter.wallet,
      ward: voter.ward,
      cardId: voter.cardId,
      tokenBalance,
      encryptedPayload: voter.encryptedPayload,
    },
    transaction: txEntry,
  });

  return sendEncrypted(res, 200, {
    success: true,
    voter: voter.name,
    tokenBalance,
  });
});

// Check token balance for a card
app.get("/balance", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const cardId = req.query.cardId || "Unknown_Card";
  const voter = getVoter(cardId);
  try {
    const balance = Number(await daoContract.getTokenBalance(voter.wallet));
    return sendEncrypted(res, 200, {
      success: true,
      cardId,
      name: voter.name,
      tokenBalance: balance,
    });
  } catch (e) {
    return sendEncrypted(res, 500, { error: "Could not read balance" });
  }
});

// Cast a real Blockchain Vote (Stateless PIN Verification)
app.post("/vote", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }
  const { encryptedPayload, proposalId, pin } = data;

  if (!encryptedPayload || !proposalId || !pin) {
    return sendEncrypted(res, 400, {
      error: "Missing encryptedPayload, proposalId, or pin",
    });
  }

  let decryptedPrivateKey;
  try {
    decryptedPrivateKey = decryptPayload(encryptedPayload, pin);
  } catch (e) {
    console.error("❌ Decryption failed: Wrong PIN or tampered payload!");
    return sendEncrypted(res, 401, { error: "Incorrect PIN. Vault failed to open." });
  }

  const signer = new ethers.Wallet(decryptedPrivateKey, provider);
  const connectedContract = daoContract.connect(signer);

  try {
    console.log(`⏳ Signing and sending TX to Blockchain using decrypted key...`);
    const tx = await connectedContract.vote(proposalId);
    console.log(`⛓️  TX Sent! Hash: ${tx.hash}`);
    const receipt = await tx.wait();
    console.log(
      `⛏️  TX Mined! BlockNumber: ${receipt.blockNumber}, Gas Used: ${receipt.gasUsed.toString()}`,
    );

    return sendEncrypted(res, 200, {
      success: true,
      transactionHash: tx.hash,
    });
  } catch (e) {
    console.error("❌ Blockchain error:", e.reason || e.message);
    return sendEncrypted(res, 500, {
      error: e.reason || "Blockchain execution failed",
    });
  }
});

// ─────────────────────────────────────────────
//  BLOCKCHAIN EVENT LISTENERS
// ─────────────────────────────────────────────
if (daoContract) {
  daoContract.on(
    "VoteCast",
    async (voterAddr, proposalId, newVoteCount, eventPayload) => {
      console.log(
        `\n🎉 EVENT RECEIVED: Real Vote Cast on Blockchain by ${voterAddr} for proposal ${proposalId}`,
      );

      const p = await daoContract.getProposal(proposalId);
      const proposalObj = {
        id: Number(p.id),
        title: p.title,
        description: p.description,
        category: p.category,
        fundsRequested: Number(p.fundsRequested),
        votes: Number(p.votes),
        status: p.active ? "active" : "inactive",
        imageUrl: p.imageUrl,
      };

      const txHash = eventPayload.log.transactionHash;

      const txEntry = {
        id: transactionFeed.length + 1,
        type: "VOTE_CAST",
        hash: txHash,
        timestamp: new Date().toISOString(),
      };
      transactionFeed.push(txEntry);

      io.emit("vote-recorded", {
        voter: currentVoter || { name: "Voter", wallet: voterAddr },
        proposal: proposalObj,
        transaction: txEntry,
      });
    },
  );
}

// ─────────────────────────────────────────────
//  SOCKET.IO
// ─────────────────────────────────────────────
io.on("connection", async (socket) => {
  console.log("🔌 Dashboard connected:", socket.id);

  const proposalsData = await readAllProposals();

  socket.emit("init", {
    proposals: proposalsData,
    transactions: transactionFeed.slice(-20),
    treasury: { totalFunds: 500000, allocated: 0, currency: "DAO Tokens" },
    currentVoter,
  });
});

// ─────────────────────────────────────────────
//  START SERVER
// ─────────────────────────────────────────────
server.listen(port, "0.0.0.0", () => {
  console.log("");
  console.log("═══════════════════════════════════════════════");
  console.log("   🏛️  OFF-GRID DAO — ACTUAL WEB3 INSTANCE");
  console.log("═══════════════════════════════════════════════");
  console.log(`   Dashboard:  http://localhost:${port}`);
  console.log("═══════════════════════════════════════════════");
});
