const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const { ethers } = require('ethers');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

const rpcUrl = process.env.RPC_URL || "http://127.0.0.1:8545";
const addressFilePath = process.env.ADDRESS_FILE || path.join(__dirname, 'address.json');
const port = Number(process.env.PORT || 3001);

// ─────────────────────────────────────────────
//  WEB3 BLOCKCHAIN SETUP (Hardhat localhost)
// ─────────────────────────────────────────────

const provider = new ethers.JsonRpcProvider(rpcUrl);

// Read deployed contract metadata generated by deployment service.
const contractJSON = require('./artifacts/contracts/OffGridDAO.sol/OffGridDAO.json');
let contractAddress = "";
let contractAbi = contractJSON.abi;
let deploymentMetadata = null;
try {
    const raw = fs.readFileSync(addressFilePath, 'utf8');
    deploymentMetadata = JSON.parse(raw);
    contractAddress = deploymentMetadata.contractAddress;
    if (Array.isArray(deploymentMetadata.abi) && deploymentMetadata.abi.length > 0) {
        contractAbi = deploymentMetadata.abi;
    }
} catch (e) {
    console.warn("⚠️ Warning: address.json not found. Run deployment script first.");
}

let daoContract;
if (contractAddress) {
    daoContract = new ethers.Contract(contractAddress, contractAbi, provider);
}

// Admin signer (Hardhat Account #0) for creating proposals and allocating tokens
const ADMIN_KEY = '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80';
const adminSigner = new ethers.Wallet(ADMIN_KEY, provider);
let adminContract;
if (daoContract) {
    adminContract = daoContract.connect(adminSigner);
}

// Transaction Feed history cache
const transactionFeed = [];

// Track which cards have been initialized with tokens
const initializedCards = new Set();

// ─────────────────────────────────────────────
//  VOTER REGISTRY (Mapped to Hardhat Private Keys)
// ─────────────────────────────────────────────
const voters = {
    'Metro_Card_001': {
        name: 'Grandma Patel',
        avatar: '👵',
        privateKey: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80',
        ward: 'Sector 7, Green Park Colony',
    },
    'Metro_Card_002': {
        name: 'Uncle Sharma',
        avatar: '👴',
        privateKey: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d',
        ward: 'Sector 12, Riverside',
    },
    'Metro_Card_003': {
        name: 'Auntie Mehra',
        avatar: '👩',
        privateKey: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a',
        ward: 'Sector 3, Market Road',
    },
};

function getVoter(cardId) {
    if (voters[cardId]) {
        const wallet = new ethers.Wallet(voters[cardId].privateKey);
        return { cardId, ...voters[cardId], wallet: wallet.address };
    }
    const fallbackWallet = new ethers.Wallet('0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6');
    return {
        cardId,
        name: 'Community Member',
        avatar: '🧑',
        privateKey: fallbackWallet.privateKey,
        wallet: fallbackWallet.address,
        ward: 'Local Resident',
    };
}

// Helper to read all proposals from blockchain
async function readAllProposals() {
    const proposalsData = [];
    if (!daoContract) return proposalsData;
    try {
        const count = await daoContract.proposalCount();
        for (let i = 1; i <= Number(count); i++) {
            const p = await daoContract.getProposal(i);
            proposalsData.push({
                id: Number(p.id),
                title: p.title,
                description: p.description,
                category: p.category,
                fundsRequested: Number(p.fundsRequested),
                votes: Number(p.votes),
                status: p.active ? 'active' : 'inactive'
            });
        }
    } catch (e) {
        console.error("Error reading proposals:", e);
    }
    return proposalsData;
}

let currentVoter = null;

function ensureContractReady(res) {
    if (!daoContract || !adminContract || !contractAddress) {
        res.status(503).json({
            error: 'Contract not ready yet. Wait for deployment to complete.',
            addressFilePath,
        });
        return false;
    }
    return true;
}

// ─────────────────────────────────────────────
//  API ROUTES
// ─────────────────────────────────────────────

app.get('/contract', (req, res) => {
    if (!contractAddress) {
        return res.status(503).json({
            error: 'Contract metadata unavailable',
            addressFilePath,
        });
    }

    res.json({
        name: (deploymentMetadata && deploymentMetadata.contractName) || 'OffGridDAO',
        contractAddress,
        abi: contractAbi,
        rpcUrl,
        deployedAt: deploymentMetadata && deploymentMetadata.deployedAt,
    });
});

// Get all proposals from the SMART CONTRACT
app.get('/proposals', async (req, res) => {
    if (!ensureContractReady(res)) return;
    res.json(await readAllProposals());
});

// Create a new proposal (from admin panel)
app.post('/proposals', async (req, res) => {
    if (!ensureContractReady(res)) return;
    const { title, description, category, fundsRequested } = req.body;
    if (!title || !fundsRequested) {
        return res.status(400).json({ error: 'Missing title or fundsRequested' });
    }

    try {
        console.log(`📝 Creating new proposal: "${title}"...`);
        const tx = await adminContract.createProposal(
            title,
            description || '',
            category || 'General',
            fundsRequested
        );
        await tx.wait();
        console.log(`✅ Proposal created on-chain! TX: ${tx.hash}`);

        // Re-read all proposals and broadcast to all dashboards
        const allProposals = await readAllProposals();
        io.emit('proposals-updated', allProposals);

        res.json({ success: true, transactionHash: tx.hash });
    } catch (e) {
        console.error("❌ Failed to create proposal:", e.reason || e.message);
        res.status(500).json({ error: e.reason || 'Failed to create proposal' });
    }
});


// NFC Scan → Identify Voter + Check Token Balance
app.get('/scan', async (req, res) => {
    if (!ensureContractReady(res)) return;
    const cardId = req.query.cardId || 'Unknown_Card';
    console.log(`\n📡 NFC SCAN DETECTED: ${cardId}`);

    const voter = getVoter(cardId);
    currentVoter = voter;

    // Allocate tokens on first scan if not already done
    let tokenBalance = 0;
    try {
        if (!initializedCards.has(cardId) && adminContract) {
            console.log(`🪙 First scan for ${cardId} — allocating 1000 tokens on-chain...`);
            const allocTx = await adminContract.allocateTokens(voter.wallet, 1000);
            await allocTx.wait();
            initializedCards.add(cardId);
        }
        // Read balance from blockchain
        tokenBalance = Number(await daoContract.getTokenBalance(voter.wallet));
    } catch (e) {
        console.error("Token allocation error:", e.reason || e.message);
    }

    const txEntry = {
        id: transactionFeed.length + 1,
        type: 'IDENTITY_VERIFY',
        hash: '0x' + require('crypto').createHash('md5').update('identity' + Date.now()).digest('hex').slice(0,40),
        timestamp: new Date().toISOString()
    };
    transactionFeed.push(txEntry);

    // Broadcast to dashboard with token balance
    io.emit('card-scanned', {
        voter: { name: voter.name, avatar: voter.avatar, wallet: voter.wallet, ward: voter.ward, cardId: voter.cardId, tokenBalance },
        transaction: txEntry,
    });

    res.json({ success: true, voter: voter.name, tokenBalance });
});

// Check token balance for a card
app.get('/balance', async (req, res) => {
    if (!ensureContractReady(res)) return;
    const cardId = req.query.cardId || 'Unknown_Card';
    const voter = getVoter(cardId);
    try {
        const balance = Number(await daoContract.getTokenBalance(voter.wallet));
        res.json({ success: true, cardId, name: voter.name, tokenBalance: balance });
    } catch (e) {
        res.status(500).json({ error: 'Could not read balance' });
    }
});

// Cast a real Blockchain Vote (Single Choice)
app.post('/vote', async (req, res) => {
    if (!ensureContractReady(res)) return;
    const { cardId, proposalId } = req.body;

    if (!cardId || !proposalId) {
        return res.status(400).json({ error: 'Missing cardId or proposalId' });
    }

    const voter = getVoter(cardId);
    const signer = new ethers.Wallet(voter.privateKey, provider);
    const connectedContract = daoContract.connect(signer);
    
    try {
        console.log(`⏳ Signing and sending TX to Blockchain for ${voter.name}...`);
        const tx = await connectedContract.vote(proposalId);
        console.log(`⛓️  TX Sent! Hash: ${tx.hash}`);
        const receipt = await tx.wait();
        console.log(`⛏️  TX Mined! BlockNumber: ${receipt.blockNumber}, Gas Used: ${receipt.gasUsed.toString()}`);

        res.json({ success: true, transactionHash: tx.hash });
    } catch (e) {
        console.error("❌ Blockchain error:", e.reason || e.message);
        res.status(500).json({ error: e.reason || 'Blockchain execution failed' });
    }
});


// ─────────────────────────────────────────────
//  BLOCKCHAIN EVENT LISTENERS
// ─────────────────────────────────────────────
if (daoContract) {
    daoContract.on("VoteCast", async (voterAddr, proposalId, newVoteCount, eventPayload) => {
        
        console.log(`\n🎉 EVENT RECEIVED: Real Vote Cast on Blockchain by ${voterAddr} for proposal ${proposalId}`);
        
        const p = await daoContract.getProposal(proposalId);
        const proposalObj = {
            id: Number(p.id),
            title: p.title,
            description: p.description,
            category: p.category,
            fundsRequested: Number(p.fundsRequested),
            votes: Number(p.votes),
            status: p.active ? 'active' : 'inactive'
        };

        const txHash = eventPayload.log.transactionHash;
        
        const txEntry = {
            id: transactionFeed.length + 1,
            type: 'VOTE_CAST',
            hash: txHash,
            timestamp: new Date().toISOString()
        };
        transactionFeed.push(txEntry);

        io.emit('vote-recorded', {
            voter: currentVoter || { name: 'Voter', wallet: voterAddr },
            proposal: proposalObj,
            transaction: txEntry,
        });
    });
}


// ─────────────────────────────────────────────
//  SOCKET.IO
// ─────────────────────────────────────────────
io.on('connection', async (socket) => {
    console.log('🔌 Dashboard connected:', socket.id);

    const proposalsData = await readAllProposals();

    socket.emit('init', {
        proposals: proposalsData,
        transactions: transactionFeed.slice(-20),
        treasury: { totalFunds: 500000, allocated: 0, currency: 'DAO Tokens' },
        currentVoter,
    });
});

// ─────────────────────────────────────────────
//  START SERVER
// ─────────────────────────────────────────────
server.listen(port, '0.0.0.0', () => {
    console.log('');
    console.log('═══════════════════════════════════════════════');
    console.log('   🏛️  OFF-GRID DAO — ACTUAL WEB3 INSTANCE');
    console.log('═══════════════════════════════════════════════');
    console.log(`   Dashboard:  http://localhost:${port}`);
    console.log('═══════════════════════════════════════════════');
});
