require("dotenv").config();
const express = require("express");
const http = require("http");
const { Server } = require("socket.io");
const cors = require("cors");
const path = require("path");
const fs = require("fs");
const { ethers } = require("ethers");
const crypto = require("crypto");
const QRCode = require("qrcode");
const {
  summarizeProposalProblem,
  generateProposalFromDescription,
  OLLAMA_MODEL,
  FEATHERLESS_MODEL,
} = require("./services/proposalSummaryService");

const app = express();
app.use(cors());
app.use(express.json());

// Serve built frontend (from frontend/dist/) at root — this is the kiosk UI
const frontendDistPath = path.join(__dirname, "..", "frontend", "dist");
if (fs.existsSync(frontendDistPath)) {
  app.use(express.static(frontendDistPath));
}

// Legacy static files (backend/public for uploads etc)
app.use(express.static(path.join(__dirname, "public")));
app.use("/uploads", express.static(path.join(__dirname, "uploads")));

// Image upload setup
const multer = require("multer");
const uploadDir = path.join(__dirname, "uploads");
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}
const storage = multer.diskStorage({
  destination: function (_req, _file, cb) {
    cb(null, uploadDir);
  },
  filename: function (_req, file, cb) {
    cb(null, Date.now() + path.extname(file.originalname));
  },
});
const upload = multer({ storage });

// In-memory map for proposal images (contract doesn't store imageUrl)
const proposalImages = {};

const server = http.createServer(app);
const io = new Server(server, { cors: { origin: "*" } });

const rpcUrl = process.env.RPC_URL || "http://127.0.0.1:8545";
const addressFilePath =
  process.env.ADDRESS_FILE || path.join(__dirname, "address.json");
const port = Number(process.env.PORT || 3001);

// ─────────────────────────────────────────────
//  WEB3 BLOCKCHAIN SETUP (Hardhat localhost)
// ─────────────────────────────────────────────

const provider = new ethers.JsonRpcProvider(rpcUrl);

// Read deployed contract metadata generated by deployment service.
const contractJSON = require("./artifacts/contracts/OffGridDAO.sol/OffGridDAO.json");
const { encrypt, decrypt } = require("./lib/crypto");
let contractAddress = "";
let contractAbi = contractJSON.abi;
let deploymentMetadata = null;
try {
  const raw = fs.readFileSync(addressFilePath, "utf8");
  deploymentMetadata = JSON.parse(raw);
  contractAddress = deploymentMetadata.contractAddress;
  if (
    Array.isArray(deploymentMetadata.abi) &&
    deploymentMetadata.abi.length > 0
  ) {
    contractAbi = deploymentMetadata.abi;
  }
} catch (e) {
  console.warn(
    "⚠️ Warning: address.json not found. Run deployment script first.",
  );
}

let daoContract;
if (contractAddress) {
  daoContract = new ethers.Contract(contractAddress, contractAbi, provider);
}

// Admin signer (Hardhat Account #0) for creating proposals and funding wallets
const ADMIN_KEY =
  "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const adminSigner = new ethers.Wallet(ADMIN_KEY, provider);
let adminContract;
if (daoContract) {
  adminContract = daoContract.connect(adminSigner);
}

// Transaction Feed history cache
const transactionFeed = [];

// ─────────────────────────────────────────────
//  DYNAMIC VOTER REGISTRY (Any NFC card can register)
// ─────────────────────────────────────────────

// Stateless PIN encryption
function encryptPayload(text, pin) {
  const key = crypto.pbkdf2Sync(pin, "salt", 100000, 32, "sha256");
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  let encrypted = cipher.update(text, "utf8", "hex");
  encrypted += cipher.final("hex");
  const authTag = cipher.getAuthTag().toString("hex");
  return { iv: iv.toString("hex"), encrypted, authTag };
}

function decryptPayload(encryptedObj, pin) {
  const key = crypto.pbkdf2Sync(pin, "salt", 100000, 32, "sha256");
  const decipher = crypto.createDecipheriv(
    "aes-256-gcm",
    key,
    Buffer.from(encryptedObj.iv, "hex"),
  );
  decipher.setAuthTag(Buffer.from(encryptedObj.authTag, "hex"));
  let decrypted = decipher.update(encryptedObj.encrypted, "hex", "utf8");
  decrypted += decipher.final("utf8");
  return decrypted;
}

// Dynamic voters map: cardId → { name, avatar, wallet, encryptedPayload, ward }
const voters = new Map();

// Hardhat account index counter — we'll use accounts #1+ for voters
// (Account #0 is admin)
let nextAccountIndex = 1;

// Pre-defined Hardhat private keys (accounts #1 through #19)
const HARDHAT_KEYS = [
  "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
  "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a",
  "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6",
  "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a",
  "0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba",
  "0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e",
  "0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356",
  "0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97",
  "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6",
  "0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897",
  "0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82",
  "0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1",
  "0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd",
  "0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa",
  "0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61",
  "0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0",
  "0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd",
  "0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0",
  "0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e",
];

function getVoter(cardId) {
  return voters.get(cardId) || null;
}

// Per-socket voter sessions
const socketSessions = new Map(); // socketId → { cardId, voter }

// Helper to read all proposals from blockchain
async function readAllProposals() {
  const proposalsData = [];
  if (!daoContract) return proposalsData;
  try {
    const count = await daoContract.proposalCount();
    for (let i = 1; i <= Number(count); i++) {
      const p = await daoContract.getProposal(i);
      proposalsData.push({
        id: Number(p.id),
        title: p.title,
        description: p.description,
        category: p.category,
        fundsRequested: Number(p.fundsRequested),
        votes: Number(p.votes),
        status: p.active ? "active" : "inactive",
        imageUrl: proposalImages[Number(p.id)] || "",
      });
    }
  } catch (e) {
    console.error("Error reading proposals:", e);
  }
  return proposalsData;
}

function ensureContractReady(res) {
  if (!daoContract || !adminContract || !contractAddress) {
    sendEncrypted(res, 503, {
      error: "Contract not ready yet. Wait for deployment to complete.",
      addressFilePath,
    });
    return false;
  }
  return true;
}

function buildEncryptedPayload(data) {
  return { payload: encrypt(JSON.stringify(data)) };
}

function sendEncrypted(res, statusCode, data) {
  return res.status(statusCode).json(buildEncryptedPayload(data));
}

function readEncryptedBody(req) {
  const body = req.body;

  if (body && typeof body === "object" && typeof body.payload === "string") {
    const decrypted = decrypt(body.payload);
    if (!decrypted) return null;
    try {
      return JSON.parse(decrypted);
    } catch (_error) {
      return null;
    }
  }

  // Backward compatibility for non-encrypted callers.
  if (body && typeof body === "object") {
    return body;
  }

  if (typeof body === "string") {
    const decrypted = decrypt(body);
    if (!decrypted) return null;
    try {
      return JSON.parse(decrypted);
    } catch (_error) {
      return null;
    }
  }

  return null;
}

// ─────────────────────────────────────────────
//  API ROUTES
// ─────────────────────────────────────────────

// Image upload endpoint
app.post("/upload", upload.single("image"), (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "No image file provided." });
  }
  const fileUrl = `/uploads/${req.file.filename}`;
  return res.json({ imageUrl: fileUrl });
});

app.get("/contract", (req, res) => {
  if (!contractAddress) {
    return sendEncrypted(res, 503, {
      error: "Contract metadata unavailable",
      addressFilePath,
    });
  }

  return sendEncrypted(res, 200, {
    name:
      (deploymentMetadata && deploymentMetadata.contractName) || "OffGridDAO",
    contractAddress,
    abi: contractAbi,
    rpcUrl,
    deployedAt: deploymentMetadata && deploymentMetadata.deployedAt,
  });
});

// Check if a card is registered
app.get("/card/:cardId", (req, res) => {
  const cardId = req.params.cardId;
  const voter = getVoter(cardId);
  if (voter) {
    return sendEncrypted(res, 200, {
      registered: true,
      name: voter.name,
      wallet: voter.wallet,
      cardId,
    });
  }
  return sendEncrypted(res, 200, { registered: false, cardId });
});

// Register a new NFC card
app.post("/register", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, { error: "Invalid encrypted payload" });
  }

  const { cardId, name, pin } = data;
  if (!cardId || !pin || pin.length < 4) {
    return sendEncrypted(res, 400, {
      error: "cardId and a 4-digit pin are required",
    });
  }

  // Check if already registered
  if (voters.has(cardId)) {
    return sendEncrypted(res, 409, {
      error: "This card is already registered",
      voter: { name: voters.get(cardId).name, cardId },
    });
  }

  // Get next Hardhat private key
  if (nextAccountIndex > HARDHAT_KEYS.length) {
    return sendEncrypted(res, 500, {
      error: "No more wallet slots available (max 19 voters)",
    });
  }

  const privateKey = HARDHAT_KEYS[nextAccountIndex - 1];
  nextAccountIndex++;

  const wallet = new ethers.Wallet(privateKey, provider);
  const voterName = name || `Voter ${cardId.slice(-4)}`;

  // Encrypt private key with user's PIN
  const encPayload = encryptPayload(privateKey, pin);

  // Allocate tokens on-chain
  try {
    console.log(`🪙 Registering card "${cardId}" as "${voterName}" → ${wallet.address}`);
    const alreadyInitialized = await daoContract.isInitialized(wallet.address);
    if (!alreadyInitialized) {
      const allocTx = await adminContract.allocateTokens(wallet.address, 1000);
      await allocTx.wait();
      console.log(`✅ 1000 tokens allocated to ${wallet.address}`);
    }
  } catch (e) {
    console.error("Token allocation error:", e.reason || e.message);
  }

  // Store voter
  const voterData = {
    name: voterName,
    avatar: "🧑",
    wallet: wallet.address,
    encryptedPayload: encPayload,
    ward: "Community Member",
    cardId,
  };
  voters.set(cardId, voterData);

  console.log(`✅ Card registered: ${cardId} → ${voterName}`);

  // Broadcast registration event
  io.emit("voter-registered", {
    cardId,
    name: voterName,
    wallet: wallet.address,
  });

  return sendEncrypted(res, 200, {
    success: true,
    voter: {
      name: voterName,
      wallet: wallet.address,
      cardId,
      encryptedPayload: encPayload,
      tokenBalance: 1000,
    },
  });
});

// Get all proposals from the SMART CONTRACT
app.get("/proposals", async (req, res) => {
  if (!ensureContractReady(res)) return;
  return sendEncrypted(res, 200, await readAllProposals());
});

// Create a new proposal (costs 200 tokens: deducted from creator)
app.post("/proposals", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }

  const { title, description, category, fundsRequested, imageUrl, encryptedPayload, pin } = data;
  if (!title || !fundsRequested) {
    return sendEncrypted(res, 400, {
      error: "Missing title or fundsRequested",
    });
  }

  if (!encryptedPayload || !pin) {
    return sendEncrypted(res, 400, {
      error: "Missing encryptedPayload or pin to authorize creation fee",
    });
  }

  let decryptedPrivateKey;
  try {
    decryptedPrivateKey = decryptPayload(encryptedPayload, pin);
  } catch (e) {
    console.error("❌ Proposal creation failed: Wrong PIN!");
    return sendEncrypted(res, 401, { error: "Incorrect PIN. Vault failed to open." });
  }

  const signer = new ethers.Wallet(decryptedPrivateKey, provider);
  const connectedContract = daoContract.connect(signer);

  try {
    console.log(`📝 Creating new proposal using signer ${signer.address}...`);
    const tx = await connectedContract.createProposal(
      title,
      description || "",
      category || "General",
      fundsRequested,
    );
    await tx.wait();
    console.log(`✅ Proposal created on-chain! TX: ${tx.hash}`);

    // Store image URL server-side (contract doesn't support it)
    const newCount = Number(await daoContract.proposalCount());
    if (imageUrl) {
      proposalImages[newCount] = imageUrl;
    }

    // Explicitly emit vote event for the creator (since they are now part of the 1 vote)
    const p = await daoContract.getProposal(newCount);
    const proposalObj = {
      id: Number(p.id),
      title: p.title,
      description: p.description,
      category: p.category,
      fundsRequested: Number(p.fundsRequested),
      votes: Number(p.votes),
      imageUrl: proposalImages[Number(p.id)] || "",
      status: p.active ? "active" : "inactive",
    };

    const txEntry = {
      id: transactionFeed.length + 1,
      type: "VOTE_CAST", // It acts as a vote
      hash: tx.hash,
      timestamp: new Date().toISOString(),
    };
    transactionFeed.push(txEntry);

    const updatedBalance = Number(await daoContract.getTokenBalance(signer.address));

    // Emit the vote-recorded so it pushes up to frontend instantly
    io.emit("vote-recorded", {
       voter: { name: "Creator", wallet: signer.address, tokenBalance: updatedBalance },
       proposal: proposalObj,
       transaction: txEntry,
    });

    // Re-read all proposals and broadcast to all dashboards
    const allProposals = await readAllProposals();
    io.emit("proposals-updated", allProposals);

    return sendEncrypted(res, 200, {
      success: true,
      transactionHash: tx.hash,
    });
  } catch (e) {
    console.error("❌ Failed to create proposal:", e.reason || e.message);
    return sendEncrypted(res, 500, {
      error: e.reason || "Failed to create proposal. Ensure you have 200 tokens and haven't voted.",
    });
  }
});

app.post("/proposals/summarize-problem", async (req, res) => {
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }

  const title = typeof data.title === "string" ? data.title.trim() : "";
  const description =
    typeof data.description === "string" ? data.description.trim() : "";

  if (!title) {
    return sendEncrypted(res, 400, {
      error: "Proposal title is required",
    });
  }

  try {
    const summary = await summarizeProposalProblem({
      title,
      description,
    });

    return sendEncrypted(res, 200, {
      summary,
      model: OLLAMA_MODEL,
    });
  } catch (error) {
    console.error("❌ Summary generation failed:", error.message);
    return sendEncrypted(res, 502, {
      error: "Could not generate proposal summary",
    });
  }
});

// AI Proposal Generation (Featherless AI)
app.post("/proposals/generate", async (req, res) => {
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }

  const userText =
    typeof data.text === "string" ? data.text.trim() : "";

  if (!userText) {
    return sendEncrypted(res, 400, {
      error: "Please describe your proposal idea",
    });
  }

  try {
    console.log(`🤖 Generating proposal from: "${userText.slice(0, 80)}..."`);
    const generated = await generateProposalFromDescription(userText);
    console.log(`✅ AI generated proposal: "${generated.title}"`);

    return sendEncrypted(res, 200, generated);
  } catch (error) {
    console.error("❌ Proposal generation failed:", error.message);
    return sendEncrypted(res, 502, {
      error: error.message || "Could not generate proposal",
    });
  }
});

// NFC Scan → Identify Voter (triggered by iOS Shortcut / Android NFC app)
// Now supports per-socket sessions via optional socketId param
app.get("/scan", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const cardId = req.query.cardId || "Unknown_Card";
  const socketId = req.query.socketId || null;
  console.log(`\n📡 NFC SCAN DETECTED: ${cardId}`);

  const voter = getVoter(cardId);

  if (!voter) {
    // Unknown card — tell frontend to show registration
    console.log(`❓ Unknown card: ${cardId} — registration required`);

    const payload = {
      type: "unregistered",
      cardId,
    };

    if (socketId && io.sockets.sockets.get(socketId)) {
      io.to(socketId).emit("card-scanned", payload);
    } else {
      io.emit("card-scanned", payload);
    }

    return sendEncrypted(res, 200, {
      success: true,
      registered: false,
      cardId,
    });
  }

  // Known card — read balance and emit to connected clients
  let tokenBalance = 0;
  try {
    const alreadyInitialized = await daoContract.isInitialized(voter.wallet);
    if (!alreadyInitialized) {
      console.log(`🪙 Re-initializing tokens for ${voter.name} on new chain...`);
      const allocTx = await adminContract.allocateTokens(voter.wallet, 1000);
      await allocTx.wait();
    }
    tokenBalance = Number(await daoContract.getTokenBalance(voter.wallet));
  } catch (e) {
    console.error("Balance read error:", e.reason || e.message);
  }

  const txEntry = {
    id: transactionFeed.length + 1,
    type: "IDENTITY_VERIFY",
    hash:
      "0x" +
      crypto
        .createHash("md5")
        .update("identity" + Date.now())
        .digest("hex")
        .slice(0, 40),
    timestamp: new Date().toISOString(),
  };
  transactionFeed.push(txEntry);

  const scanPayload = {
    type: "registered",
    voter: {
      name: voter.name,
      avatar: voter.avatar,
      wallet: voter.wallet,
      ward: voter.ward,
      cardId: voter.cardId,
      tokenBalance: null, // Hidden until PIN verified
      encryptedPayload: voter.encryptedPayload,
    },
    transaction: txEntry,
  };

  // Emit to specific socket if provided, otherwise broadcast
  if (socketId && io.sockets.sockets.get(socketId)) {
    io.to(socketId).emit("card-scanned", scanPayload);
  } else {
    io.emit("card-scanned", scanPayload);
  }

  return sendEncrypted(res, 200, {
    success: true,
    registered: true,
    voter: voter.name,
    tokenBalance: null, // Hidden
  });
});

// Check token balance for a card
app.get("/balance", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const cardId = req.query.cardId || "Unknown_Card";
  const voter = getVoter(cardId);
  if (!voter) {
    return sendEncrypted(res, 404, { error: "Card not registered" });
  }
  try {
    const balance = Number(await daoContract.getTokenBalance(voter.wallet));
    return sendEncrypted(res, 200, {
      success: true,
      cardId,
      name: voter.name,
      tokenBalance: balance,
    });
  } catch (e) {
    return sendEncrypted(res, 500, { error: "Could not read balance" });
  }
});

// Verify PIN to securely return balance
app.post("/verify-pin", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, { error: "Invalid encrypted payload" });
  }
  const { encryptedPayload, pin } = data;

  if (!encryptedPayload || !pin) {
    return sendEncrypted(res, 400, { error: "Missing encryptedPayload or pin" });
  }

  let decryptedPrivateKey;
  try {
    decryptedPrivateKey = decryptPayload(encryptedPayload, pin);
  } catch (e) {
    console.error("❌ Balance check failed: Wrong PIN!");
    return sendEncrypted(res, 401, { error: "Incorrect PIN. Vault failed to open." });
  }

  // If we decrypted it successfully, we know this is the actual voter.
  const signer = new ethers.Wallet(decryptedPrivateKey, provider);
  
  try {
    const balance = Number(await daoContract.getTokenBalance(signer.address));
    return sendEncrypted(res, 200, {
      success: true,
      tokenBalance: balance,
    });
  } catch (e) {
    return sendEncrypted(res, 500, { error: "Could not read balance from chain" });
  }
});

// Cast a real Blockchain Vote (Stateless PIN Verification)
app.post("/vote", async (req, res) => {
  if (!ensureContractReady(res)) return;
  const data = readEncryptedBody(req);
  if (!data) {
    return sendEncrypted(res, 400, {
      error: "Invalid encrypted payload",
    });
  }
  const { encryptedPayload, proposalId, pin } = data;

  if (!encryptedPayload || !proposalId || !pin) {
    return sendEncrypted(res, 400, {
      error: "Missing encryptedPayload, proposalId, or pin",
    });
  }

  let decryptedPrivateKey;
  try {
    decryptedPrivateKey = decryptPayload(encryptedPayload, pin);
  } catch (e) {
    console.error("❌ Decryption failed: Wrong PIN or tampered payload!");
    return sendEncrypted(res, 401, { error: "Incorrect PIN. Vault failed to open." });
  }

  const signer = new ethers.Wallet(decryptedPrivateKey, provider);
  const connectedContract = daoContract.connect(signer);

  try {
    console.log(`⏳ Signing and sending TX to Blockchain using decrypted key...`);
    const tx = await connectedContract.vote(proposalId);
    console.log(`⛓️  TX Sent! Hash: ${tx.hash}`);
    const receipt = await tx.wait();
    console.log(
      `⛏️  TX Mined! BlockNumber: ${receipt.blockNumber}, Gas Used: ${receipt.gasUsed.toString()}`,
    );

    // Explicitly fetch and emit to guarantee dashboard updates
    const p = await daoContract.getProposal(proposalId);
    const proposalObj = {
      id: Number(p.id),
      title: p.title,
      description: p.description,
      category: p.category,
      fundsRequested: Number(p.fundsRequested),
      votes: Number(p.votes),
      imageUrl: proposalImages[Number(p.id)] || "",
      status: p.active ? "active" : "inactive",
    };

    const txEntry = {
      id: transactionFeed.length + 1,
      type: "VOTE_CAST",
      hash: tx.hash,
      timestamp: new Date().toISOString(),
    };
    transactionFeed.push(txEntry);

    const updatedBalance = Number(await daoContract.getTokenBalance(signer.address));

    io.emit("vote-recorded", {
      voter: { name: "Voter", wallet: signer.address, tokenBalance: updatedBalance },
      proposal: proposalObj,
      transaction: txEntry,
    });

    return sendEncrypted(res, 200, {
      success: true,
      transactionHash: tx.hash,
    });
  } catch (e) {
    console.error("❌ Blockchain error:", e.reason || e.message);
    return sendEncrypted(res, 500, {
      error: e.reason || "Blockchain execution failed",
    });
  }
});

// ─────────────────────────────────────────────
//  V2: TUNNEL INFO — Read cloudflared public URL
// ─────────────────────────────────────────────

const CLOUDFLARED_LOG = path.join(__dirname, "..", "cloudflared.log");
let cachedTunnelUrl = null;

function extractTunnelUrl() {
  if (cachedTunnelUrl) return cachedTunnelUrl;
  try {
    if (!fs.existsSync(CLOUDFLARED_LOG)) return null;
    const log = fs.readFileSync(CLOUDFLARED_LOG, "utf8");
    const match = log.match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/);
    if (match) {
      cachedTunnelUrl = match[0];
      console.log(`🌐 Cloudflare Tunnel detected: ${cachedTunnelUrl}`);
    }
    return cachedTunnelUrl || null;
  } catch (_) {
    return null;
  }
}

// Reset cached URL when the log file is deleted/recreated
setInterval(() => {
  if (cachedTunnelUrl && fs.existsSync(CLOUDFLARED_LOG)) {
    const log = fs.readFileSync(CLOUDFLARED_LOG, "utf8");
    if (!log.includes(cachedTunnelUrl)) cachedTunnelUrl = null;
  } else if (cachedTunnelUrl && !fs.existsSync(CLOUDFLARED_LOG)) {
    cachedTunnelUrl = null;
  }
}, 30000);

app.get("/tunnel-info", (req, res) => {
  const tunnelUrl = extractTunnelUrl();
  // Get LAN IP
  const nets = require("os").networkInterfaces();
  let lanIp = "localhost";
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        lanIp = net.address;
        break;
      }
    }
  }
  return res.json({
    tunnelUrl: tunnelUrl || null,
    lanUrl: `http://${lanIp}:${port}`,
    tunnelReady: !!tunnelUrl,
  });
});

// ─────────────────────────────────────────────
//  V2: INVITE CODES — Virtual NFC cards for remote users
// ─────────────────────────────────────────────

// In-memory invite store: code → { label, cardId, used, expiresAt, createdAt }
const invites = new Map();

function generateInviteCode() {
  const part = () => crypto.randomBytes(2).toString("hex").toUpperCase();
  return `TDAO-${part()}-${part()}`;
}

// Generate a new invite code (creates a virtual cardId)
app.post("/invites/generate", (req, res) => {
  const body = req.body || {};
  const label = (body.label || "Remote Voter").slice(0, 64);
  const code = generateInviteCode();
  const cardId = `INVITE-${code}`;
  const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(); // 7 days

  invites.set(code, { label, cardId, used: false, expiresAt, createdAt: new Date().toISOString() });
  console.log(`🎟️  Invite generated: ${code} → cardId: ${cardId}`);

  const tunnelUrl = extractTunnelUrl();
  const baseUrl = tunnelUrl || `http://localhost:${port}`;
  const joinUrl = `${baseUrl}/?invite=${code}`;

  return res.json({ code, cardId, label, joinUrl, expiresAt });
});

// Get QR code image for an invite code
app.get("/invites/qr/:code", async (req, res) => {
  const code = req.params.code;
  const invite = invites.get(code);
  if (!invite) return res.status(404).json({ error: "Invite not found" });

  const tunnelUrl = extractTunnelUrl();
  const baseUrl = tunnelUrl || `http://localhost:${port}`;
  const joinUrl = `${baseUrl}/?invite=${code}`;

  try {
    const png = await QRCode.toBuffer(joinUrl, { width: 300, margin: 2 });
    res.setHeader("Content-Type", "image/png");
    res.setHeader("Cache-Control", "no-cache");
    return res.send(png);
  } catch (err) {
    return res.status(500).json({ error: "QR generation failed" });
  }
});

// List all active invites
app.get("/invites", (req, res) => {
  const list = [];
  for (const [code, inv] of invites.entries()) {
    list.push({ code, label: inv.label, used: inv.used, expiresAt: inv.expiresAt, createdAt: inv.createdAt });
  }
  return res.json(list);
});

// Redeem an invite code — triggers same flow as NFC card scan
app.post("/invites/redeem", async (req, res) => {
  const body = req.body || {};
  const { code, socketId } = body;

  if (!code) return res.status(400).json({ error: "Invite code required" });

  const invite = invites.get(code);
  if (!invite) return res.status(404).json({ error: "Invite code not found or expired" });
  if (invite.used) return res.status(409).json({ error: "This invite has already been used" });

  const now = new Date();
  if (new Date(invite.expiresAt) < now) {
    return res.status(410).json({ error: "Invite code has expired" });
  }

  // Treat the virtual cardId exactly like a physical NFC card scan
  const { cardId } = invite;
  const voter = getVoter(cardId);

  if (!voter) {
    // Not yet registered — show registration modal (same as unregistered NFC card)
    const payload = { type: "unregistered", cardId };
    if (socketId && io.sockets.sockets.get(socketId)) {
      io.to(socketId).emit("card-scanned", payload);
    } else {
      io.emit("card-scanned", payload);
    }
    console.log(`🎟️  Invite ${code} redeemed (unregistered) → cardId: ${cardId}`);
    return res.json({ success: true, registered: false, cardId });
  }

  // Already registered — emit voter session
  invite.used = true;
  let tokenBalance = 0;
  try {
    tokenBalance = Number(await daoContract.getTokenBalance(voter.wallet));
  } catch (_) {}

  const scanPayload = {
    type: "registered",
    voter: {
      name: voter.name,
      avatar: voter.avatar,
      wallet: voter.wallet,
      ward: voter.ward,
      cardId: voter.cardId,
      tokenBalance: null,
      encryptedPayload: voter.encryptedPayload,
    },
  };

  if (socketId && io.sockets.sockets.get(socketId)) {
    io.to(socketId).emit("card-scanned", scanPayload);
  } else {
    io.emit("card-scanned", scanPayload);
  }

  console.log(`🎟️  Invite ${code} redeemed (registered) → voter: ${voter.name}`);
  return res.json({ success: true, registered: true, voter: voter.name });
});

// ─────────────────────────────────────────────
//  SOCKET.IO — Per-socket sessions
// ─────────────────────────────────────────────
io.on("connection", async (socket) => {
  console.log("🔌 Client connected:", socket.id);

  const proposalsData = await readAllProposals();

  socket.emit("init", {
    proposals: proposalsData,
    transactions: transactionFeed.slice(-20),
    treasury: { totalFunds: 500000, allocated: 0, currency: "DAO Tokens" },
    socketId: socket.id, // Send socketId so frontend can use it for NFC shortcut linking
  });

  socket.on("disconnect", () => {
    console.log("🔌 Client disconnected:", socket.id);
    socketSessions.delete(socket.id);
  });
});

// ─────────────────────────────────────────────
//  SPA FALLBACK — serve index.html for client-side routing
// ─────────────────────────────────────────────
if (fs.existsSync(frontendDistPath)) {
  app.get("*", (req, res) => {
    res.sendFile(path.join(frontendDistPath, "index.html"));
  });
}

// ─────────────────────────────────────────────
//  START SERVER
// ─────────────────────────────────────────────
server.listen(port, "0.0.0.0", () => {
  console.log("");
  console.log("═══════════════════════════════════════════════");
  console.log("   🏛️  TAP DAO — Mobile Kiosk Server");
  console.log("═══════════════════════════════════════════════");
  console.log(`   Local:   http://localhost:${port}`);

  // Show LAN IP for kiosk phones
  const nets = require("os").networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === "IPv4" && !net.internal) {
        console.log(`   Network: http://${net.address}:${port}`);
      }
    }
  }

  console.log("═══════════════════════════════════════════════");
  console.log(`   Registered cards: ${voters.size}`);
  console.log(`   Contract: ${contractAddress || "Not deployed"}`);
  console.log("═══════════════════════════════════════════════");
});
